logging:
  level:
    root: info


spring:
  data:
    mongodb:
      database: test_db
      port: 27017
      host: 192.168.1.22

rocketmq:
  name-server: 192.168.1.22:9876
  producer:
    group: filecoin-group
